#!/bin/bash

echo "=========================================="
echo "Configuração de Port Forwarding"
echo "=========================================="
echo ""
echo "Para permitir que seus amigos acessem o servidor de casa,"
echo "você precisa configurar Port Forwarding no seu roteador."
echo ""
echo "IP Local do Servidor: 192.168.1.86"
echo ""
echo "Portas que precisam ser redirecionadas:"
echo ""
echo "  80   (HTTP)       → 192.168.1.86:80"
echo "  443  (HTTPS)      → 192.168.1.86:443"
echo "  3724 (Auth WoW)   → 192.168.1.86:3724"
echo "  8085 (World WoW)  → 192.168.1.86:8085"
echo ""
echo "=========================================="
echo "Passos para configurar no roteador:"
echo "=========================================="
echo ""
echo "1. Acesse o painel do seu roteador:"
echo "   - Geralmente: http://192.168.1.1 ou http://192.168.0.1"
echo "   - Usuário/Senha: admin/admin (ou veja etiqueta do roteador)"
echo ""
echo "2. Procure por uma das opções:"
echo "   - Port Forwarding"
echo "   - Virtual Server"
echo "   - NAT"
echo "   - Redirecionamento de Portas"
echo ""
echo "3. Adicione as regras acima"
echo ""
echo "4. Salve e reinicie o roteador"
echo ""
echo "=========================================="
echo "Verificar IP Público:"
echo "=========================================="
echo ""

PUBLIC_IP=$(curl -s ifconfig.me)
echo "Seu IP Público atual: $PUBLIC_IP"
echo ""
echo "Seus amigos devem usar este IP para conectar!"
echo ""
echo "=========================================="
echo "Testar Portas Abertas:"
echo "=========================================="
echo ""
echo "Use este site para testar se as portas estão abertas:"
echo "https://www.yougetsignal.com/tools/open-ports/"
echo ""
echo "Ou use o comando:"
echo "nc -zv $PUBLIC_IP 80"
echo "nc -zv $PUBLIC_IP 443"
echo "nc -zv $PUBLIC_IP 3724"
echo "nc -zv $PUBLIC_IP 8085"
echo ""
